name: Build Android APK and AAB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Debug APK and AAB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Build Ionic App
      run: ionic build --configuration=debug

    - name: Install Capacitor Android
      run: npx cap add android

    - name: Generate Debug APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Generate AAB
      run: |
        cd android
        ./gradlew bundleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-app.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Debug AAB
      uses: actions/upload-artifact@v3
      with:
        name: debug-app.aab
        path: android/app/build/outputs/bundle/debug/app-debug.aab
